name: Build and Deploy

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npx parcel build ./src/index.html --public-url ./

      - name: Move assets to the dist folder
        run: mv src/assets dist
      
      - name: Rename dist folder to docs
        run: mv dist docs

      - name: Commit docs folder
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git checkout dist
          git add docs
          git commit -m "Upload page"
          git push -u origin dist